# Generated by Django 5.1.5 on 2025-02-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_lcm', '0013_fix_hardware_lifecycle_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseassignment',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licenseassignment',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
