# Generated by Django 5.1.5 on 2025-02-23 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_lcm', '0014_licenseassignment_end_licenseassignment_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportcontractassignment',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='netbox_lcm.supportcontract'),
        ),
        migrations.AlterField(
            model_name='supportcontractassignment',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='dcim.device'),
        ),
    ]
