# Generated by Django 5.1.5 on 2025-04-28 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_lcm', '0015_alter_supportcontractassignment_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportcontractassignment',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='netbox_lcm.licenseassignment'),
        ),
        migrations.AlterField(
            model_name='supportcontractassignment',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='netbox_lcm.supportsku'),
        ),
    ]
