# Generated by Django 5.2.2 on 2025-06-15 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_lcm', '0017_hardwarelifecycleplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardwarelifecycle',
            options={'ordering': ['assigned_object_type', 'end_of_support']},
        ),
    ]
