# Generated by Django 5.1.8 on 2025-06-01 07:17

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('extras', '0123_journalentry_kind_default'),
        ('netbox_lcm', '0017_hardwarelifecycleplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardwarelifecycle',
            options={'ordering': ['assigned_object_type', 'end_of_support']},
        ),
        migrations.CreateModel(
            name='SoftwareProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('major_version', models.CharField(max_length=100)),
                ('minor_version', models.CharField(max_length=100)),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('end_of_security_date', models.DateField(blank=True, null=True)),
                ('end_of_support_date', models.DateField(blank=True, null=True)),
                ('documentation_url', models.URLField(blank=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcim.platform')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('platform', 'major_version', 'minor_version', 'end_of_support_date', 'release_date'),
                'unique_together': {('platform', 'major_version', 'minor_version')},
            },
        ),
        migrations.CreateModel(
            name='SoftwareRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('version', models.CharField(max_length=100)),
                ('version_alias', models.CharField(max_length=100)),
                ('status', models.CharField(default='accepted', max_length=50)),
                ('device_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.devicerole')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcim.devicetype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='netbox_lcm.softwareproduct')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['product__name', 'version'],
                'unique_together': {('product', 'version', 'device_type', 'device_role')},
            },
        ),
        migrations.CreateModel(
            name='SoftwareAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('assigned', models.DateTimeField(auto_now_add=True)),
                ('currently_active', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netbox_lcm.softwarerelease')),
            ],
            options={
                'ordering': ['-assigned'],
                'constraints': [models.UniqueConstraint(fields=('device', 'release'), name='unique_device_release_history')],
            },
        ),
    ]
