# Generated by Django 5.2.2 on 2025-06-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_lcm', '0017_hardwarelifecycleplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardwarelifecycle',
            options={'ordering': ['assigned_object_type', 'end_of_support']},
        ),
        migrations.AddField(
            model_name='supportcontractassignment',
            name='support_coverage_status',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
