# Generated by Django 5.2.4 on 2025-08-11 12:14

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0129_fix_script_paths'),
        ('netbox_lcm', '0018_alter_hardwarelifecycle_softwareproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAssessmentType',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('default_retention_days', models.PositiveIntegerField(default=90)),
                ('higher_is_better', models.BooleanField(default=True)),
                ('ui_badge', models.CharField(default='default', max_length=32)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['slug'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ExternalAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('assessment_type', models.CharField(db_index=True, max_length=64)),
                ('target_id', models.PositiveBigIntegerField(db_index=True)),
                ('source', models.CharField(db_index=True, max_length=128)),
                ('source_run_id', models.CharField(blank=True, max_length=128, null=True)),
                ('external_reference', models.CharField(blank=True, max_length=256, null=True)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('retention_days', models.PositiveIntegerField(default=90)),
                ('status', models.CharField(db_index=True, default='unknown', max_length=16)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('is_latest', models.BooleanField(db_index=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['assessment_type', 'target_type', 'target_id', '-observed_at'], name='netbox_lcm__assessm_0ae802_idx'), models.Index(fields=['source', 'observed_at'], name='netbox_lcm__source_6372cd_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_latest', True)), fields=('assessment_type', 'target_type', 'target_id'), name='uniq_latest_per_type_target')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
