# Generated by Django 5.2.2 on 2025-07-27 03:16

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0207_remove_redundant_indexes'),
        ('extras', '0128_tableconfig'),
        ('netbox_lcm', '0018_alter_hardwarelifecycle_softwareproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceBackupPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('critical', models.BooleanField(default=False)),
                ('evaluate_status', models.BooleanField(default=True)),
                ('backup_system', models.CharField(default='none', max_length=50)),
                ('destination', models.TextField(blank=True)),
                ('method', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_policies', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Device Backup Policy',
                'verbose_name_plural': 'Device Backup Policies',
            },
        ),
        migrations.CreateModel(
            name='DeviceBackupResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('backup_date', models.DateField()),
                ('status', models.CharField(default='unknown', max_length=20)),
                ('details', models.TextField(blank=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='netbox_lcm.devicebackuppolicy')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['-backup_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='devicebackuppolicy',
            constraint=models.UniqueConstraint(models.F('device'), models.F('backup_system'), name='netbox_lcm_devicebackuppolicy_unique_device_backupsystem', violation_error_message='Assigned Backup Systems must be unique.'),
        ),
        migrations.AddConstraint(
            model_name='devicebackupresult',
            constraint=models.UniqueConstraint(models.F('policy'), models.F('backup_date'), name='netbox_lcm_devicebackupresult_unique_policy_backupdate', violation_error_message='Backup Date must be unique per backup policy.'),
        ),
    ]
