# Generated by Django 5.1.8 on 2025-06-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('extras', '0123_journalentry_kind_default'),
        ('netbox_lcm', '0018_alter_hardwarelifecycle_options_softwareproduct_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SoftwareAssignment',
            new_name='SoftwareReleaseAssignment',
        ),
        migrations.AddField(
            model_name='softwarerelease',
            name='notes',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
