# Generated by Django 5.2.4 on 2025-08-12 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_lcm', '0019_externalassessmenttype_externalassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalassessment',
            name='assessment_type',
            field=models.ForeignKey(db_column='assessment_type', on_delete=django.db.models.deletion.PROTECT, to='netbox_lcm.externalassessmenttype'),
        ),
    ]
