# Generated by Django 5.1.8 on 2025-06-02 04:20

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('extras', '0123_journalentry_kind_default'),
        ('netbox_lcm', '0019_rename_softwareassignment_softwarereleaseassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTypeFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('device_types', models.ManyToManyField(blank=True, related_name='devicetype_families', to='dcim.devicetype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='softwarerelease',
            name='devicetype_family',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='netbox_lcm.devicetypefamily'),
            preserve_default=False,
        ),
    ]
