# Generated by Django 5.1.8 on 2025-06-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('netbox_lcm', '0020_devicetypefamily_softwarerelease_devicetype_family'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='softwarerelease',
            unique_together={('product', 'version', 'devicetype_family', 'device_role')},
        ),
        migrations.AlterField(
            model_name='devicetypefamily',
            name='device_types',
            field=models.ManyToManyField(blank=True, related_name='device_type_families', to='dcim.devicetype'),
        ),
        migrations.RemoveField(
            model_name='softwarerelease',
            name='device_type',
        ),
    ]
