# Generated by Django 5.1.8 on 2025-06-02 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('netbox_lcm', '0021_alter_softwarerelease_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetypefamily',
            name='manufacturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='device_type_families', to='dcim.manufacturer'),
            preserve_default=False,
        ),
    ]
