# Generated by Django 5.1.8 on 2025-06-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_lcm', '0022_devicetypefamily_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareproduct',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
