# Generated by Django 5.1.8 on 2025-06-08 04:06

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('extras', '0123_journalentry_kind_default'),
        ('netbox_lcm', '0023_alter_softwareproduct_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softwarerelease',
            name='status',
        ),
        migrations.CreateModel(
            name='SoftwareReleaseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(default='accepted', max_length=50)),
                ('device_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcim.devicerole')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_assignments', to='netbox_lcm.softwarerelease')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['release', 'device_role'],
                'unique_together': {('release', 'device_role')},
            },
        ),
    ]
