# Generated by Django 5.1.8 on 2025-06-08 08:02

import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0123_journalentry_kind_default'),
        ('netbox_lcm', '0024_remove_softwarerelease_status_softwarereleasestatus'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='softwarerelease',
            unique_together={('product', 'version', 'devicetype_family')},
        ),
        migrations.CreateModel(
            name='SoftwareCVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('published_date', models.DateField()),
                ('last_modified_date', models.DateField(blank=True, null=True)),
                ('documentation_url', models.URLField()),
                ('description', models.TextField(blank=True, default='')),
                ('cve_severity', models.CharField(default='None', max_length=100)),
                ('agreed_severity', models.CharField(default='None', max_length=100)),
                ('cvss', models.FloatField(blank=True, null=True)),
                ('cvss_v2', models.FloatField(blank=True, null=True)),
                ('cvss_v3', models.FloatField(blank=True, null=True)),
                ('fix', models.CharField(blank=True, default='', max_length=255)),
                ('workaround_avail', models.BooleanField(default=True)),
                ('comments', models.TextField(blank=True, default='')),
                ('affected_softwares', models.ManyToManyField(blank=True, related_name='corresponding_cves', to='netbox_lcm.softwarerelease')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Software CVE',
                'ordering': ('agreed_severity', 'name'),
            },
        ),
        migrations.RemoveField(
            model_name='softwarerelease',
            name='device_role',
        ),
    ]
