# Generated by Django 5.1.8 on 2025-06-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_lcm', '0025_alter_softwarerelease_unique_together_softwarecve_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='softwarereleaseassignment',
            options={'ordering': ['-assigned_on']},
        ),
        migrations.RenameField(
            model_name='softwarereleaseassignment',
            old_name='assigned',
            new_name='assigned_on',
        ),
        migrations.RemoveField(
            model_name='softwarereleaseassignment',
            name='currently_active',
        ),
        migrations.AddField(
            model_name='softwarereleaseassignment',
            name='unassigned_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
