# Generated by Django 5.1.8 on 2025-06-08 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_lcm', '0026_alter_softwarereleaseassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='softwarerelease',
            unique_together={('product', 'version')},
        ),
        migrations.AddField(
            model_name='softwarereleasestatus',
            name='devicetype_family',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='netbox_lcm.devicetypefamily'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='softwarerelease',
            name='devicetype_family',
        ),
    ]
