# Generated by Django 5.1.8 on 2025-06-08 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_lcm', '0027_alter_softwarerelease_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwarereleaseassignment',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netbox_lcm.softwarereleasestatus'),
        ),
    ]
