# Generated by Django 5.1.8 on 2025-06-08 13:33

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0123_journalentry_kind_default'),
        ('netbox_lcm', '0028_alter_softwarereleaseassignment_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareReleaseCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('image_file_name', models.CharField(max_length=100)),
                ('download_url', models.URLField(blank=True)),
                ('image_file_checksum', models.CharField(blank=True, max_length=256)),
                ('hashing_algorithm', models.CharField(blank=True, default='', max_length=50)),
                ('devicetype_family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netbox_lcm.devicetypefamily')),
                ('software_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_assignments', to='netbox_lcm.softwarerelease')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Software Release Statuse',
                'ordering': ['software_release', 'devicetype_family'],
                'unique_together': {('software_release', 'devicetype_family')},
            },
        ),
        migrations.AlterField(
            model_name='softwarereleaseassignment',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netbox_lcm.softwarereleasecompatibility'),
        ),
        migrations.DeleteModel(
            name='SoftwareReleaseStatus',
        ),
    ]
