# Generated by Django 5.1.8 on 2025-06-08 13:49

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('extras', '0123_journalentry_kind_default'),
        ('netbox_lcm', '0029_softwarereleasecompatibility_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareReleaseCompatibilityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(max_length=32)),
                ('compatibility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_by_role', to='netbox_lcm.softwarereleasecompatibility')),
                ('device_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcim.devicerole')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'unique_together': {('compatibility', 'device_role')},
            },
        ),
    ]
